project:
  type: website

  render:
  - 404.qmd
  - index.qmd
  - general/*.qmd
  - part-01/*.qmd
  - part-02/*.qmd
  - part-03/*.qmd
  - part-04/*.qmd
  - part-05/*.qmd
  - part-06/*.qmd
  - part-07/*.qmd
  - part-08/*.qmd
  - part-10/*.qmd
  - assignments/*.qmd

website:
  title: "Programming with Python"
  repo-url: https://github.com/beyondsimulations/Introduction-to-Python
  site-url: https://beyondsimulations.github.io/Introduction-to-Python
  repo-actions: [edit, source, issue]
  bread-crumbs: true
  reader-mode: true
  sidebar:
    style: floating
    collapse-level: 1 
    search: true
    contents:
      - text: "Welcome"
        href: index.qmd
      - text: "Syllabus"
        href: general/syllabus.qmd
      - text: "***"
      - section: "01 Introduction "
        contents:
          - text: "Lecture"
            href: part-01/lecture-introduction.qmd
          - text: "Tutorial"
            href: part-01/tutorial-introduction.qmd
      - section: "02 Control Flow"
        contents:
          - text: "Lecture"
            href: part-02/lecture-control.qmd
          - text: "Tutorial"
            href: part-02/tutorial-control.qmd
      - section: "03 Functions"
        contents:
          - text: "Lecture"
            href: part-03/lecture-functions.qmd
          - text: "Tutorial"
            href: part-03/tutorial-functions.qmd
      - section: "04 Dimensions"
        contents:
          - text: "Lecture"
            href: part-04/lecture-dimensions.qmd
          - text: "Tutorial"
            href: part-04/tutorial-dimensions.qmd
      - section: "05 Errors"
        contents:
          - text: "Lecture"
            href: part-05/lecture-errors.qmd
          - text: "Tutorial"
            href: part-05/tutorial-errors.qmd
      - section: "06 Modules"
        contents:
          - text: "Lecture"
            href: part-06/lecture-modules.qmd
          - text: "Tutorial"
            href: part-06/tutorial-modules.qmd
      - section: "07 Scientific Computing"
        contents:
          - text: "Lecture"
            href: part-07/lecture-scientific.qmd
          - text: "Tutorial"
            href: part-07/tutorial-scientific.qmd
      - section: "08 Tabular and AI"
        contents:
          - text: "Lecture"
            href: part-08/lecture-pandas.qmd
          - text: "Tutorial"
            href: part-08/tutorial-pandas.qmd
      - section: "10 Projects"
        contents:
          - text: "Lecture"
            href: part-10/lecture-projects.qmd
      - text: "***"
      - section: "Assignments"
        contents:
          - text: "01 Assignment"
            href: assignments/assignment-1.qmd
          - text: "02 Assignment"
            href: assignments/assignment-2.qmd
      - text: "Cheatsheet"
        href: general/cheatsheet.qmd
      - text: "FAQs"
        href: general/faq.qmd
      - text: "Literature"
        href: general/literature.qmd
  page-footer: 
    center: "Programming with Python, Tobias Vlćek</br>CC BY-NC-SA 4.0" 
    right: 
      - icon: github
        href: https://github.com/beyondsimulations/Introduction-to-Python
      - icon: linkedin
        href: https://linkedin.com/in/tobiasvlcek

format:
  html:
    theme: litera
    toc: true
    highlight-style: arrow
    code-overflow: wrap
    linkcolor: "#a60000"
    slide-number: true
    code-copy: true
    code-link: true
    toc-location: right
  pdf:
    documentclass: report
    geometry:
      - margin=1in
    fontfamily: roboto
    fontfamilyoptions: sfdefault
    colorlinks: true
    include-in-header: 
      text: |
        \usepackage{fvextra}
        \DefineVerbatimEnvironment{Highlighting}{Verbatim}{breaklines,commandchars=\\\{\}}

execute:
  freeze: true


