project:
  type: website
  output-dir: docs

website:
  title: "Programming with Python"
  repo-url: https://github.com/beyondsimulations/Introduction-to-Python
  site-url: https://beyondsimulations.github.io/Introduction-to-Python
  bread-crumbs: true
  sidebar:
    style: floating
    collapse-level: 1 
    search: true
    contents:
      - text: "Welcome"
        href: index.qmd
      - text: "Syllabus"
        href: general/syllabus.qmd
      - section: "01 Introduction "
        contents:
          - text: "Lecture"
            href: part-01/lecture-introduction.qmd
          - text: "Tutorial"
            href: part-01/tutorial-introduction.qmd
      - section: "02 Control Flow"
        contents:
          - text: "Lecture"
            href: part-02/lecture-control.qmd
          - text: "Tutorial"
            href: part-02/tutorial-control.qmd
      - section: "03 Functions"
        contents:
          - text: "Lecture"
            href: part-03/lecture-functions.qmd
          - text: "Tutorial"
            href: part-03/tutorial-functions.qmd
      - section: "04 Dimensions"
        contents:
          - text: "Lecture"
            href: part-04/lecture-dimensions.qmd
          - text: "Tutorial"
            href: part-04/tutorial-dimensions.qmd
      - section: "05 Errors"
        contents:
          - text: "Lecture"
            href: part-05/lecture-errors.qmd
          - text: "Tutorial"
            href: part-05/tutorial-errors.qmd
      - section: "Assignments"
        contents:
          - text: "01 Assignment"
            href: assignments/assignment-1.qmd
          - text: "02 Assignment"
            href: assignments/assignment-2.qmd
      - text: "FAQs"
        href: general/faq.qmd
      - text: "Literature"
        href: general/literature.qmd
  page-footer: 
    center: "Programming with Python, Tobias Vlćek</br>CC BY-NC-SA 4.0" 
    right: 
      - icon: github
        href: https://github.com/beyondsimulations/Introduction-to-Python
      - icon: linkedin
        href: https://linkedin.com/in/tobiasvlcek

format:
  html:
    theme: litera
    css: styles.css
    toc: true

execute:
  cache: true


