project:
  type: website
  output-dir: docs

website:
  title: "Programming with Python"
  bread-crumbs: true
  sidebar:
    style: "floating"
    search: true
    contents:
      - text: "Welcome"
        href: index.qmd
      - text: "Syllabus"
        href: syllabus.qmd
      - section: "01 Introduction "
        contents:
          - text: "Lecture"
            href: part-1/lecture-introduction.qmd
          - text: "Tutorial"
            href: part-1/tutorial-introduction.qmd
      - section: "02 Control"
        contents:
          - text: "Lecture"
            href: part-2/lecture-control.qmd
          - text: "Tutorial"
            href: part-2/tutorial-control.qmd
      - section: "Assignments"
        contents:
          - text: "01 Assignment"
            href: assignments/assignment-1.qmd
          - text: "02 Assignment"
            href: assignments/assignment-2.qmd
      - text: "FAQs"
        href: faq.qmd
      - text: "Literature"
        href: literature.qmd
  page-footer: 
    center: "Programming with Python 2024, Tobias Vlćek" 
    right: 
      - icon: github
        href: https://github.com/beyondsimulations
      - icon: linkedin
        href: https://linkedin.com/in/tobiasvlcek

format:
  html:
    theme: litera
    css: styles.css
    toc: true



