project:
  type: website
  output-dir: docs

website:
  title: "Programming with Python"
  bread-crumbs: true
  sidebar:
    style: "floating"
    search: true
    contents:
      - text: "About the course"
        href: about.qmd
      - section: "I - Introduction"
        contents:
          - text: "Lecture"
            href: part-1/lecture-introduction.qmd
          - text: "Tutorial"
            href: part-1/tutorial-introduction.qmd
  page-footer: 
    center: "Tobias Vlćek, 2024" 
    right: 
      - icon: github
        href: https://github.com/beyondsimulations
      - icon: linkedin
        href: https://linkedin.com/in/tobiasvlcek

format:
  html:
    theme: litera
    css: styles.css
    toc: true



