project:
  type: website

  render:
    - 404.qmd
    - index.qmd
    - general/*.qmd
    - part-01/*.qmd
    - part-02/*.qmd
    - part-03/*.qmd
    - part-04/*.qmd
    - part-05/*.qmd
    - part-06/*.qmd
    - part-07/*.qmd
    - part-08/*.qmd
    - part-09/*.qmd
    - part-10/*.qmd
    - assignments/*.qmd

website:
  title: "Programming with Python"
  repo-url: https://github.com/beyondsimulations/Introduction-to-Python
  site-url: https://beyondsimulations.github.io/Introduction-to-Python
  repo-actions: [source, issue]
  bread-crumbs: true
  sidebar:
    style: floating
    logo: https://images.beyondsimulations.com/lectures/mj-python.png
    collapse-level: 1
    search: true
    contents:
      - text: "Welcome"
        href: index.qmd
      - text: "Syllabus"
        href: general/syllabus.qmd
      - text: "***"
      - section: "01 Introduction "
        contents:
          - text: "Lecture"
            href: part-01/lecture-introduction.qmd
          - text: "Tutorial"
            href: part-01/tutorial-introduction.qmd
      - section: "02 Control Flow"
        contents:
          - text: "Lecture"
            href: part-02/lecture-control.qmd
          - text: "Tutorial"
            href: part-02/tutorial-control.qmd
      - section: "03 Functions"
        contents:
          - text: "Lecture"
            href: part-03/lecture-functions.qmd
          - text: "Tutorial"
            href: part-03/tutorial-functions.qmd
      - section: "04 Dimensions"
        contents:
          - text: "Lecture"
            href: part-04/lecture-dimensions.qmd
          - text: "Tutorial"
            href: part-04/tutorial-dimensions.qmd
      - section: "05 Errors"
        contents:
          - text: "Lecture"
            href: part-05/lecture-errors.qmd
          - text: "Tutorial"
            href: part-05/tutorial-errors.qmd
      - section: "06 Modules"
        contents:
          - text: "Lecture"
            href: part-06/lecture-modules.qmd
          - text: "Tutorial"
            href: part-06/tutorial-modules.qmd
      - section: "07 Scientific Computing"
        contents:
          - text: "Lecture"
            href: part-07/lecture-scientific.qmd
          - text: "Tutorial"
            href: part-07/tutorial-scientific.qmd
      - section: "08 Pandas and AI"
        contents:
          - text: "Lecture"
            href: part-08/lecture-pandas.qmd
          - text: "Tutorial"
            href: part-08/tutorial-pandas.qmd
      - section: "09 Plotting"
        contents:
          - text: "Lecture"
            href: part-09/lecture-plotting.qmd
          - text: "Tutorial"
            href: part-09/tutorial-plotting.qmd
      - section: "10 Projects"
        contents:
          - text: "Lecture"
            href: part-10/lecture-projects.qmd
      - text: "***"
      - section: "Assignments"
        contents:
          - text: "01 Assignment"
            href: assignments/assignment-1.qmd
          - text: "02 Assignment"
            href: assignments/assignment-2.qmd
      - text: "Cheatsheet"
        href: general/cheatsheet.qmd
      - text: "Chatbot"
        href: general/chat.qmd
      - text: "FAQs"
        href: general/faq.qmd
      - text: "Literature"
        href: general/literature.qmd
  page-footer:
    center: "Programming with Python, Tobias Vlćek</br>CC BY-NC-SA 4.0"
    right:
      - icon: github
        href: https://github.com/beyondsimulations/Introduction-to-Python
      - icon: linkedin
        href: https://linkedin.com/in/tobiasvlcek
      - icon: envelope
        href: mailto:vlcek@beyondsimulations.com
      - icon: privacy
        href: general/privacy.qmd
format:
  html:
    html:
      theme: [litera, ../styles.scss]
    toc: true
    highlight-style: arrow
    code-overflow: wrap
    linkcolor: "#a60000"
    slide-number: true
    code-copy: true
    code-link: true
    toc-location: right
    include-in-header:
      - general/header.html
    include-after-body:
      text: |
        <script>
          window.difyChatbotConfig = {
            token: 'XCLkkdVV1UtPggWt',
            baseUrl: 'https://flow.byndsim.com',
            systemVariables: {
              // user_id: 'YOU CAN DEFINE USER ID HERE',
            },
            containerProps: {
              style: {
                  backgroundColor: '#ffffff',
                  borderRadius: '0px',
              },
            },
          }
        </script>
        <script
          src="https://flow.byndsim.com/embed.min.js"
          id="XCLkkdVV1UtPggWt"
          defer>
        </script>
        <style>
          #dify-chatbot-bubble-button {
            background-color: #8C3048 !important;
          }
          #dify-chatbot-bubble-window {
            width: 24rem !important;
            height: 80vh !important;
            position: fixed !important;
          }
        </style>
  pdf:
    documentclass: report
    geometry:
      - margin=1in
    fontfamily: roboto
    fontfamilyoptions: sfdefault
    colorlinks: true
    include-in-header:
      text: |
        \usepackage{fvextra}
        \DefineVerbatimEnvironment{Highlighting}{Verbatim}{breaklines,commandchars=\\\{\}}

execute:
  freeze: true
