project:
  type: website
  post-render:
    - helpers/convert_qmd_to_md.py
  render:
    - index.qmd
    - 404.qmd
    - general/*.qmd
    - lectures/*.qmd
    - tutorials/*.qmd
    - assignments/*.qmd

website:
  title: "Programming with Python"
  repo-url: https://github.com/beyondsimulations/Introduction-to-Python
  site-url: https://beyondsimulations.github.io/Introduction-to-Python
  repo-actions: [source, issue]
  bread-crumbs: true
  sidebar:
    style: floating
    logo: https://images.beyondsimulations.com/lectures/mj-python.png
    collapse-level: 1
    search: true
    contents:
      - text: "Welcome"
        href: index.qmd
      - text: "Syllabus"
        href: general/syllabus.qmd
      - text: "***"
      - section: "01 Introduction "
        contents:
          - text: "Lecture"
            href: lectures/lec_01_introduction.qmd
          - text: "Tutorial"
            href: tutorials/tut_01_introduction.qmd
      - section: "02 Control Flow"
        contents:
          - text: "Lecture"
            href: lectures/lec_02_control.qmd
          - text: "Tutorial"
            href: tutorials/tut_02_control.qmd
      - section: "03 Functions"
        contents:
          - text: "Lecture"
            href: lectures/lec_03_functions.qmd
          - text: "Tutorial"
            href: tutorials/tut_03_functions.qmd
      - section: "04 Dimensions"
        contents:
          - text: "Lecture"
            href: lectures/lec_04_dimensions.qmd
          - text: "Tutorial"
            href: tutorials/tut_04_dimensions.qmd
      - section: "05 Errors"
        contents:
          - text: "Lecture"
            href: lectures/lec_05_errors.qmd
          - text: "Tutorial"
            href: tutorials/tut_05_errors.qmd
      - section: "06 Modules"
        contents:
          - text: "Lecture"
            href: lectures/lec_06_modules.qmd
          - text: "Tutorial"
            href: tutorials/tut_06_modules.qmd
      - section: "07 Scientific Computing"
        contents:
          - text: "Lecture"
            href: lectures/lec_07_scientific.qmd
          - text: "Tutorial"
            href: tutorials/tut_07_scientific.qmd
      - section: "08 Pandas and AI"
        contents:
          - text: "Lecture"
            href: lectures/lec_08_pandas.qmd
          - text: "Tutorial"
            href: tutorials/tut_08_pandas.qmd
      - section: "09 Plotting"
        contents:
          - text: "Lecture"
            href: lectures/lec_09_plotting.qmd
          - text: "Tutorial"
            href: tutorials/tut_09_plotting.qmd
      - section: "10 Projects"
        contents:
          - text: "Lecture"
            href: lectures/lec_10_projects.qmd
      - text: "***"
      - section: "Assignments"
        contents:
          - text: "01 Assignment"
            href: assignments/assignment_01.qmd
          - text: "02 Assignment"
            href: assignments/assignment_02.qmd
      - text: "Cheatsheet"
        href: general/cheatsheet.qmd
      - text: "FAQs"
        href: general/faq.qmd
      - text: "Literature"
        href: general/literature.qmd
  page-footer:
    center: "Programming with Python, Tobias Vlćek</br>CC BY-NC-SA 4.0"
    right:
      - icon: github
        href: https://github.com/beyondsimulations/Applied-Optimization
      - icon: linkedin
        href: https://linkedin.com/in/tobiasvlcek
      - icon: envelope
        href: mailto:vlcek@beyondsimulations.com
      - icon: lock
        href: general/privacy.qmd
format:
  html:
    theme:
      - default
      - styles.scss
      - brand
    toc: true
    highlight-style: arrow
    code-copy: true
    code-link: true
    toc-location: right
    code-overflow: wrap
    html-math-method:
      method: mathjax
      url: "https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"
    include-in-header:
      - general/header.html
    include-after-body:
      text: |
        <script src="https://cdn.jsdelivr.net/gh/beyondsimulations/web-embedded-chat@latest/floating-chat.js"></script>
        <script>
            new UniversalChatWidget({
                title: "Python Assistant",
                apiEndpoint: "https://model-proxy.vlcek-4b4.workers.dev/api",
                model: "python-programming",
                userMessageOpacity: 0.5,
                assistantMessageOpacity: 0.5,
                position: "bottom-right",
                windowHeight: 800,
                debug: true
            });
        </script>
  hugo-md: default
  typst:
    papersize: a4

format-links:
  - html
  - format: typst
    text: PDF
    icon: file-pdf

execute:
  freeze: true

brand: _brand.yml
