---
title: "Detailed Structure of the Lecture"
---
## Part I: Introduction to Programming with Python

**Welcome and Introduction (I)**\
Basics of Python syntax, variables, data types

**Control Structures for Your Code (II)**\
Loops (for, while), conditional statements (if-else), basic logic

**Building Reusable Functions (III)**\
Functions, arguments, return values, scope

**Handling Data in more than one Dimension (IV)**\
Tuples, Lists, Sets, Dictionaries, and I/O

**Handling Errors and Strings (V)**\
Exceptions, try-except blocks, strings, regular expressions

## Part II: Data Science with Python

**Using Modules and Random Numbers (VI)**\
Standard libraries, random numbers and how to use them

**NumPy and Pandas for Scientific Computing (VII)**\
Data manipulation with Pandas, array operations with NumPy

**Plotting Data (VIII)**\
Matplotlib, Seaborne based on hand-on examples

**First steps into A.I. (IX)**\
A brief intro to machine learning concepts

## Part III: Programming Projects

**Your first Project I (X)**\
Choose your project that ties together concepts from the course

**Your first Project II (XI)**\
Progress your group-project under assistance

**Your first Project III (XII)**\
Finalize your group-project with your team

**Presentations and Discussion (XIII)**\
Present your group’s work and the learnings you have made