---
title: "Syllabus"
subtitle: "This years course structure"

html:
    theme: litera
    highlight-style: breezedark
    linkcolor: "#a60000"
    code-copy: true
    code-link: true
    toc: true
---
# Part I 
## Introduction to Programming with Python

In the first part, an introduction to the basic concepts of programming in Python is provided. Students will learn the Python syntax, data types, as well as how to implement loops, functions, and object classes in Python. We will introduce core Python libraries, too, including NumPy and Pandas. Once these concepts are understood, we will learn how they can be used to solve problems.

## Lectures

**Welcome and Introduction (I)**\
Basics of Python syntax, variables, data types

**Control Structures for Your Code (II)**\
String methods, Comparisons, conditional statements, loops

**Building Reusable Functions (III)**\
Functions, arguments, return values, scope, classes

**Handling Data in more than one Dimension (IV)**\
Tuples, Lists, Sets, Dictionaries, and basic I/O

**Handling Errors and Strings (V)**\
Exceptions, try-except blocks, regular expressions

# Part II 
## Data Science with Python

In the second part, we will cover basic data science tools in Python referring to data manipulation, descriptive and explorative analysis as well as visualization. At the end, an outlook will be provided on the next steps in Python, including statistical analysis and machine learning.

## Lectures

**Using Modules and Random Numbers (VI)**\
Standard libraries, random numbers and how to use them

**NumPy and Pandas for Scientific Computing (VII)**\
Data manipulation with Pandas, array operations with NumPy

**Plotting Data (VIII)**\
Matplotlib, Seaborne based on hand-on examples

**First steps into A.I. (IX)**\
A brief intro to machine learning concepts

# Part III 
## Programming Projects

In the third part, students will be assigned mini projects in Python where they can apply their new knowledge in groups on a project of their choice. Each group will present their results and get feedback at the end of the semester.

## Lectures

**Your first Project I (X)**\
Choose your project that ties together concepts from the course

**Your first Project II (XI)**\
Progress your group-project under assistance

**Your first Project III (XII)**\
Finalize your group-project with your team

**Presentations and Discussion (XIII)**\
Present your group’s work and the learnings you have made